# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := geos
DEFS_Debug := \
	'-D_DARWIN_USE_64_BIT_INODE=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_REENTRANT=1' \
	'-DDEBUG' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-Os \
	-gdwarf-2 \
	-mmacosx-version-min=10.5 \
	-arch x86_64 \
	-Wall \
	-Wendif-labels \
	-W \
	-Wno-unused-parameter

# Flags passed to only C files.
CFLAGS_C_Debug := \
	-fno-strict-aliasing

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fno-strict-aliasing

# Flags passed to only ObjC files.
CFLAGS_OBJC_Debug :=

# Flags passed to only ObjC++ files.
CFLAGS_OBJCC_Debug :=

INCS_Debug := \
	-I/Users/zacmcc/.node-gyp/0.8.14/src \
	-I/Users/zacmcc/.node-gyp/0.8.14/deps/uv/include \
	-I/Users/zacmcc/.node-gyp/0.8.14/deps/v8/include \
	-I$(srcdir)/../geos \
	-I$(srcdir)/../geos/capi \
	-I$(srcdir)/../geos/include

DEFS_Release := \
	'-D_DARWIN_USE_64_BIT_INODE=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_REENTRANT=1' \
	'-DNDEBUG'

# Flags passed to all source files.
CFLAGS_Release := \
	-Os \
	-gdwarf-2 \
	-mmacosx-version-min=10.5 \
	-arch x86_64 \
	-Wall \
	-Wendif-labels \
	-W \
	-Wno-unused-parameter

# Flags passed to only C files.
CFLAGS_C_Release := \
	-fno-strict-aliasing

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fno-strict-aliasing

# Flags passed to only ObjC files.
CFLAGS_OBJC_Release :=

# Flags passed to only ObjC++ files.
CFLAGS_OBJCC_Release :=

INCS_Release := \
	-I/Users/zacmcc/.node-gyp/0.8.14/src \
	-I/Users/zacmcc/.node-gyp/0.8.14/deps/uv/include \
	-I/Users/zacmcc/.node-gyp/0.8.14/deps/v8/include \
	-I$(srcdir)/../geos \
	-I$(srcdir)/../geos/capi \
	-I$(srcdir)/../geos/include

OBJS := \
	$(obj).target/$(TARGET)/../geos/capi/geos_c.o \
	$(obj).target/$(TARGET)/../geos/capi/geos_ts_c.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/Angle.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/BoundaryNodeRule.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/CentroidArea.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/CentroidLine.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/CentroidPoint.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/CGAlgorithms.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/ConvexHull.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/distance/DiscreteHausdorffDistance.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/distance/DistanceToPoint.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/HCoordinate.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/InteriorPointArea.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/InteriorPointLine.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/InteriorPointPoint.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/LineIntersector.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/locate/IndexedPointInAreaLocator.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/locate/PointOnGeometryLocator.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/locate/SimplePointInAreaLocator.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/MCPointInRing.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/MinimumDiameter.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/NotRepresentableException.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/PointLocator.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/RayCrossingCounter.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/RobustDeterminant.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/SimplePointInRing.o \
	$(obj).target/$(TARGET)/../geos/src/algorithm/SIRtreePointInRing.o \
	$(obj).target/$(TARGET)/../geos/src/geom/Coordinate.o \
	$(obj).target/$(TARGET)/../geos/src/geom/CoordinateArraySequence.o \
	$(obj).target/$(TARGET)/../geos/src/geom/CoordinateArraySequenceFactory.o \
	$(obj).target/$(TARGET)/../geos/src/geom/CoordinateSequence.o \
	$(obj).target/$(TARGET)/../geos/src/geom/CoordinateSequenceFactory.o \
	$(obj).target/$(TARGET)/../geos/src/geom/Dimension.o \
	$(obj).target/$(TARGET)/../geos/src/geom/Envelope.o \
	$(obj).target/$(TARGET)/../geos/src/geom/Geometry.o \
	$(obj).target/$(TARGET)/../geos/src/geom/GeometryCollection.o \
	$(obj).target/$(TARGET)/../geos/src/geom/GeometryComponentFilter.o \
	$(obj).target/$(TARGET)/../geos/src/geom/GeometryFactory.o \
	$(obj).target/$(TARGET)/../geos/src/geom/GeometryList.o \
	$(obj).target/$(TARGET)/../geos/src/geom/IntersectionMatrix.o \
	$(obj).target/$(TARGET)/../geos/src/geom/LinearRing.o \
	$(obj).target/$(TARGET)/../geos/src/geom/LineSegment.o \
	$(obj).target/$(TARGET)/../geos/src/geom/LineString.o \
	$(obj).target/$(TARGET)/../geos/src/geom/Location.o \
	$(obj).target/$(TARGET)/../geos/src/geom/MultiLineString.o \
	$(obj).target/$(TARGET)/../geos/src/geom/MultiPoint.o \
	$(obj).target/$(TARGET)/../geos/src/geom/MultiPolygon.o \
	$(obj).target/$(TARGET)/../geos/src/geom/Point.o \
	$(obj).target/$(TARGET)/../geos/src/geom/Polygon.o \
	$(obj).target/$(TARGET)/../geos/src/geom/PrecisionModel.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/AbstractPreparedPolygonContains.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/BasicPreparedGeometry.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedGeometry.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedGeometryFactory.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedLineString.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedLineStringIntersects.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedPoint.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedPolygon.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedPolygonContains.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedPolygonContainsProperly.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedPolygonCovers.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedPolygonIntersects.o \
	$(obj).target/$(TARGET)/../geos/src/geom/prep/PreparedPolygonPredicate.o \
	$(obj).target/$(TARGET)/../geos/src/geom/Triangle.o \
	$(obj).target/$(TARGET)/../geos/src/geom/util/ComponentCoordinateExtracter.o \
	$(obj).target/$(TARGET)/../geos/src/geom/util/CoordinateOperation.o \
	$(obj).target/$(TARGET)/../geos/src/geom/util/GeometryCombiner.o \
	$(obj).target/$(TARGET)/../geos/src/geom/util/GeometryEditor.o \
	$(obj).target/$(TARGET)/../geos/src/geom/util/GeometryTransformer.o \
	$(obj).target/$(TARGET)/../geos/src/geom/util/ShortCircuitedGeometryVisitor.o \
	$(obj).target/$(TARGET)/../geos/src/geom/util/SineStarFactory.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/Depth.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GeomGraphDirectedEdge.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GeomGraphDirectedEdgeStar.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GeomGraphEdge.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/EdgeEnd.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/EdgeEndStar.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/EdgeIntersectionList.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/EdgeList.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/EdgeNodingValidator.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GeomGraphEdgeRing.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GeometryGraph.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GraphComponent.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/index/MonotoneChainEdge.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/index/MonotoneChainIndexer.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/index/SegmentIntersector.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/index/SimpleEdgeSetIntersector.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/index/SimpleMCSweepLineIntersector.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/index/SimpleSweepLineIntersector.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/index/GeomGraphSweepLineEvent.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/index/SweepLineSegment.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/Label.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GeomGraphNode.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/NodeFactory.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GeomGraphNodeMap.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/GeomGraphPlanarGraph.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/Position.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/Quadrant.o \
	$(obj).target/$(TARGET)/../geos/src/geomgraph/TopologyLocation.o \
	$(obj).target/$(TARGET)/../geos/src/index/bintree/Bintree.o \
	$(obj).target/$(TARGET)/../geos/src/index/bintree/BinTreeInterval.o \
	$(obj).target/$(TARGET)/../geos/src/index/bintree/BinTreeKey.o \
	$(obj).target/$(TARGET)/../geos/src/index/bintree/BinTreeNode.o \
	$(obj).target/$(TARGET)/../geos/src/index/bintree/BinTreeNodeBase.o \
	$(obj).target/$(TARGET)/../geos/src/index/bintree/BinTreeRoot.o \
	$(obj).target/$(TARGET)/../geos/src/index/chain/MonotoneChain.o \
	$(obj).target/$(TARGET)/../geos/src/index/chain/MonotoneChainBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/index/chain/MonotoneChainOverlapAction.o \
	$(obj).target/$(TARGET)/../geos/src/index/chain/MonotoneChainSelectAction.o \
	$(obj).target/$(TARGET)/../geos/src/index/intervalrtree/IntervalRTreeBranchNode.o \
	$(obj).target/$(TARGET)/../geos/src/index/intervalrtree/IntervalRTreeLeafNode.o \
	$(obj).target/$(TARGET)/../geos/src/index/intervalrtree/IntervalRTreeNode.o \
	$(obj).target/$(TARGET)/../geos/src/index/intervalrtree/SortedPackedIntervalRTree.o \
	$(obj).target/$(TARGET)/../geos/src/index/quadtree/DoubleBits.o \
	$(obj).target/$(TARGET)/../geos/src/index/quadtree/IntervalSize.o \
	$(obj).target/$(TARGET)/../geos/src/index/quadtree/Key.o \
	$(obj).target/$(TARGET)/../geos/src/index/quadtree/QuadTreeNode.o \
	$(obj).target/$(TARGET)/../geos/src/index/quadtree/NodeBase.o \
	$(obj).target/$(TARGET)/../geos/src/index/quadtree/Quadtree.o \
	$(obj).target/$(TARGET)/../geos/src/index/quadtree/Root.o \
	$(obj).target/$(TARGET)/../geos/src/index/strtree/AbstractNode.o \
	$(obj).target/$(TARGET)/../geos/src/index/strtree/AbstractSTRtree.o \
	$(obj).target/$(TARGET)/../geos/src/index/strtree/Interval.o \
	$(obj).target/$(TARGET)/../geos/src/index/strtree/ItemBoundable.o \
	$(obj).target/$(TARGET)/../geos/src/index/strtree/SIRtree.o \
	$(obj).target/$(TARGET)/../geos/src/index/strtree/STRtree.o \
	$(obj).target/$(TARGET)/../geos/src/index/sweepline/SweepLineEvent.o \
	$(obj).target/$(TARGET)/../geos/src/index/sweepline/SweepLineIndex.o \
	$(obj).target/$(TARGET)/../geos/src/index/sweepline/SweepLineInterval.o \
	$(obj).target/$(TARGET)/../geos/src/inlines.o \
	$(obj).target/$(TARGET)/../geos/src/io/ByteOrderDataInStream.o \
	$(obj).target/$(TARGET)/../geos/src/io/ByteOrderValues.o \
	$(obj).target/$(TARGET)/../geos/src/io/CLocalizer.o \
	$(obj).target/$(TARGET)/../geos/src/io/ParseException.o \
	$(obj).target/$(TARGET)/../geos/src/io/StringTokenizer.o \
	$(obj).target/$(TARGET)/../geos/src/io/Unload.o \
	$(obj).target/$(TARGET)/../geos/src/io/WKBReader.o \
	$(obj).target/$(TARGET)/../geos/src/io/WKBWriter.o \
	$(obj).target/$(TARGET)/../geos/src/io/WKTReader.o \
	$(obj).target/$(TARGET)/../geos/src/io/WKTWriter.o \
	$(obj).target/$(TARGET)/../geos/src/io/Writer.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/ExtractLineByLocation.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/LengthIndexedLine.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/LengthIndexOfPoint.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/LengthLocationMap.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/LinearGeometryBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/LinearIterator.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/LinearLocation.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/LocationIndexOfLine.o \
	$(obj).target/$(TARGET)/../geos/src/linearref/LocationIndexOfPoint.o \
	$(obj).target/$(TARGET)/../geos/src/noding/BasicSegmentString.o \
	$(obj).target/$(TARGET)/../geos/src/noding/FastNodingValidator.o \
	$(obj).target/$(TARGET)/../geos/src/noding/FastSegmentSetIntersectionFinder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/IntersectionAdder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/IntersectionFinderAdder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/IteratedNoder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/MCIndexNoder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/MCIndexSegmentSetMutualIntersector.o \
	$(obj).target/$(TARGET)/../geos/src/noding/NodedSegmentString.o \
	$(obj).target/$(TARGET)/../geos/src/noding/NodingValidator.o \
	$(obj).target/$(TARGET)/../geos/src/noding/Octant.o \
	$(obj).target/$(TARGET)/../geos/src/noding/OrientedCoordinateArray.o \
	$(obj).target/$(TARGET)/../geos/src/noding/ScaledNoder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/SegmentIntersectionDetector.o \
	$(obj).target/$(TARGET)/../geos/src/noding/SegmentNode.o \
	$(obj).target/$(TARGET)/../geos/src/noding/SegmentNodeList.o \
	$(obj).target/$(TARGET)/../geos/src/noding/SegmentString.o \
	$(obj).target/$(TARGET)/../geos/src/noding/SegmentStringUtil.o \
	$(obj).target/$(TARGET)/../geos/src/noding/SimpleNoder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/SingleInteriorIntersectionFinder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/snapround/HotPixel.o \
	$(obj).target/$(TARGET)/../geos/src/noding/snapround/MCIndexPointSnapper.o \
	$(obj).target/$(TARGET)/../geos/src/noding/snapround/MCIndexSnapRounder.o \
	$(obj).target/$(TARGET)/../geos/src/noding/snapround/SimpleSnapRounder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/BufferBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/BufferInputLineSimplifier.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/BufferOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/BufferParameters.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/BufferSubgraph.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/OffsetCurveBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/OffsetCurveSetBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/OffsetSegmentGenerator.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/RightmostEdgeFinder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/buffer/SubgraphDepthLocater.o \
	$(obj).target/$(TARGET)/../geos/src/operation/distance/ConnectedElementLocationFilter.o \
	$(obj).target/$(TARGET)/../geos/src/operation/distance/ConnectedElementPointFilter.o \
	$(obj).target/$(TARGET)/../geos/src/operation/distance/DistanceOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/distance/GeometryLocation.o \
	$(obj).target/$(TARGET)/../geos/src/operation/GeometryGraphOperation.o \
	$(obj).target/$(TARGET)/../geos/src/operation/IsSimpleOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/linemerge/EdgeString.o \
	$(obj).target/$(TARGET)/../geos/src/operation/linemerge/LineMergeDirectedEdge.o \
	$(obj).target/$(TARGET)/../geos/src/operation/linemerge/LineMergeEdge.o \
	$(obj).target/$(TARGET)/../geos/src/operation/linemerge/LineMergeGraph.o \
	$(obj).target/$(TARGET)/../geos/src/operation/linemerge/LineMerger.o \
	$(obj).target/$(TARGET)/../geos/src/operation/linemerge/LineSequencer.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/EdgeSetNoder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/ElevationMatrix.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/ElevationMatrixCell.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/LineBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/MaximalEdgeRing.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/MinimalEdgeRing.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/OverlayNodeFactory.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/OverlayOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/PointBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/PolygonBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/snap/GeometrySnapper.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/snap/LineStringSnapper.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/snap/SnapIfNeededOverlayOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/snap/SnapOverlayOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/validate/FuzzyPointLocator.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/validate/OffsetPointGenerator.o \
	$(obj).target/$(TARGET)/../geos/src/operation/overlay/validate/OverlayResultValidator.o \
	$(obj).target/$(TARGET)/../geos/src/operation/polygonize/EdgeRing.o \
	$(obj).target/$(TARGET)/../geos/src/operation/polygonize/PolygonizeDirectedEdge.o \
	$(obj).target/$(TARGET)/../geos/src/operation/polygonize/PolygonizeEdge.o \
	$(obj).target/$(TARGET)/../geos/src/operation/polygonize/PolygonizeGraph.o \
	$(obj).target/$(TARGET)/../geos/src/operation/polygonize/Polygonizer.o \
	$(obj).target/$(TARGET)/../geos/src/operation/predicate/RectangleContains.o \
	$(obj).target/$(TARGET)/../geos/src/operation/predicate/RectangleIntersects.o \
	$(obj).target/$(TARGET)/../geos/src/operation/predicate/SegmentIntersectionTester.o \
	$(obj).target/$(TARGET)/../geos/src/operation/relate/EdgeEndBuilder.o \
	$(obj).target/$(TARGET)/../geos/src/operation/relate/EdgeEndBundle.o \
	$(obj).target/$(TARGET)/../geos/src/operation/relate/EdgeEndBundleStar.o \
	$(obj).target/$(TARGET)/../geos/src/operation/relate/RelateComputer.o \
	$(obj).target/$(TARGET)/../geos/src/operation/relate/RelateNode.o \
	$(obj).target/$(TARGET)/../geos/src/operation/relate/RelateNodeFactory.o \
	$(obj).target/$(TARGET)/../geos/src/operation/relate/RelateNodeGraph.o \
	$(obj).target/$(TARGET)/../geos/src/operation/relate/RelateOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/sharedpaths/SharedPathsOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/union/CascadedPolygonUnion.o \
	$(obj).target/$(TARGET)/../geos/src/operation/union/CascadedUnion.o \
	$(obj).target/$(TARGET)/../geos/src/operation/union/PointGeometryUnion.o \
	$(obj).target/$(TARGET)/../geos/src/operation/union/UnaryUnionOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/ConnectedInteriorTester.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/ConsistentAreaTester.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/IndexedNestedRingTester.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/IsValidOp.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/QuadtreeNestedRingTester.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/RepeatedPointTester.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/SimpleNestedRingTester.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/SweeplineNestedRingTester.o \
	$(obj).target/$(TARGET)/../geos/src/operation/valid/TopologyValidationError.o \
	$(obj).target/$(TARGET)/../geos/src/planargraph/algorithm/ConnectedSubgraphFinder.o \
	$(obj).target/$(TARGET)/../geos/src/planargraph/DirectedEdge.o \
	$(obj).target/$(TARGET)/../geos/src/planargraph/DirectedEdgeStar.o \
	$(obj).target/$(TARGET)/../geos/src/planargraph/Edge.o \
	$(obj).target/$(TARGET)/../geos/src/planargraph/Node.o \
	$(obj).target/$(TARGET)/../geos/src/planargraph/NodeMap.o \
	$(obj).target/$(TARGET)/../geos/src/planargraph/PlanarGraph.o \
	$(obj).target/$(TARGET)/../geos/src/planargraph/Subgraph.o \
	$(obj).target/$(TARGET)/../geos/src/precision/CommonBits.o \
	$(obj).target/$(TARGET)/../geos/src/precision/CommonBitsOp.o \
	$(obj).target/$(TARGET)/../geos/src/precision/CommonBitsRemover.o \
	$(obj).target/$(TARGET)/../geos/src/precision/EnhancedPrecisionOp.o \
	$(obj).target/$(TARGET)/../geos/src/precision/SimpleGeometryPrecisionReducer.o \
	$(obj).target/$(TARGET)/../geos/src/simplify/DouglasPeuckerLineSimplifier.o \
	$(obj).target/$(TARGET)/../geos/src/simplify/DouglasPeuckerSimplifier.o \
	$(obj).target/$(TARGET)/../geos/src/simplify/LineSegmentIndex.o \
	$(obj).target/$(TARGET)/../geos/src/simplify/TaggedLineSegment.o \
	$(obj).target/$(TARGET)/../geos/src/simplify/TaggedLinesSimplifier.o \
	$(obj).target/$(TARGET)/../geos/src/simplify/TaggedLineString.o \
	$(obj).target/$(TARGET)/../geos/src/simplify/TaggedLineStringSimplifier.o \
	$(obj).target/$(TARGET)/../geos/src/simplify/TopologyPreservingSimplifier.o \
	$(obj).target/$(TARGET)/../geos/src/util/Assert.o \
	$(obj).target/$(TARGET)/../geos/src/util/GeometricShapeFactory.o \
	$(obj).target/$(TARGET)/../geos/src/util/math.o \
	$(obj).target/$(TARGET)/../geos/src/util/Profiler.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))
$(OBJS): GYP_OBJCFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(CFLAGS_OBJC_$(BUILDTYPE))
$(OBJS): GYP_OBJCXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(CFLAGS_OBJCC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
